### ISSUE TITLE
Improve GooeyJr's greeting message including using a first message in NOTICE mode

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/GooeyJr#48]
This is to make it more visible that the bot has engaged a user, for those new to IRC that may not notice a PM sitting who-knows-where in their IRC channel.

First message should this be of NOTICE type, be a nice greeting, plus reference for the user to look for additional information in a PM somewhere, including current limitations in place due to spam fighting policies. If anything goes wrong they could try Discord instead or try to send a PM to a channel OP (including how to identify such a user)

The remaining messages should still be of the private message type.

**Comment by iojw** [comment]
Thanks for this 🙂

I was working on implementing this functionality a while ago but I couldn’t quite the NOTICE function to work with the irc library (it’s lacking quite a bit of docmentation).

See https://github.com/nandub/hubot-irc/blob/master/src/irc.coffee for the library implementation
