### ISSUE TITLE
Discord double-expands links

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/GooeyJr#60]
![screenshot_20181209-115158](https://user-images.githubusercontent.com/6791585/49692223-6ce82c80-fba9-11e8-8c10-7f0cc0ce45b7.png)

When a full link is posted/bridged into Discord a preview appears. Our Hubot _also_ posts a preview if you have an issue id in a message, like #1234 - including if that exists inside a full link. Suddenly you end up with two identical previews on Discord, one from it natively expanding links then again for the bot reposting a link.

This can likely be solved by wrapping the bots link in `<` and `>` to produce `<https://link.to/issue>`

Also triggered if the link is posted on the Slack side

**Comment by iojw** [comment]
Wrapping the link in `<>` does not appear to work. I tried to address this in 10ed1d593861758a894a7cdb3216625ae9c43189 by removing the link in replies which are triggered by links. We could look into extracting more info from the GH api to make the bot more useful.

**Comment by dkienenb** [comment]
It seems the solution would be to not post the link if the message contains the link.

**Comment by iojw** [comment]
@dkienenb Yep, that’s what https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2FMovingBlocks%2FGooeyJr%2Fissues%2F60 implements.

**Comment by iojw** [comment]
@dkienenb Yep that’s what https://github.com/MovingBlocks/GooeyJr/commit/10ed1d593861758a894a7cdb3216625ae9c43189 implements.
