### ISSUE TITLE
Minor grammatical error

### ISSUE THREAD

**Issue by dkienenb** [MovingBlocks/GooeyJr#63]
![Screenshot at 2019-06-24 09-20-02](https://user-images.githubusercontent.com/31170484/60022195-56935100-9661-11e9-83f2-bfb3ba6d9de1.png)

**Comment by dkienenb** [comment]
In case above isn't quite readable: @GooeyJr Psst. This channel is *current moderated* due to *the spam* Check out the private message I've sent you for more information and how to gain voice.

**Comment by iojw** [comment]
Closed by #64 - thanks @majordwarf
